name: Build APK with Java 17

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK 17 with distribution
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu

    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: --no-daemon app:assembleRelease

    - name: Display files in directory
      run: |
        ls app/build/outputs/apk/release
    
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        alias: key.alias
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        signingKeyBase64: ${{ secrets.KEYSTORE_CONTENT }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Delete current release assets
      uses: andreaswilli/delete-release-assets-action@v2.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Prerelease-alpha
        deleteOnlyFromDrafts: false

    - name: Tag Repo
      uses: richardsimko/update-tag@v1
      with:
        tag_name: Prerelease-alpha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Alpha
      uses: softprops/action-gh-release@v1
      if: ${{  success() }}
      with:
        tag: ${{ github.ref_name }}
        tag_name: Prerelease-alpha
        files: app/build/outputs/apk/release/*
        prerelease: true
        generate_release_notes: true

    - name: Find APKs
      run: |
        mkdir APKs
        find app/build/outputs/apk/release -name "*.apk" -exec cp {} APKs \;

    - name: Upload to telegram
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        CACHE_CHAT_ID: ${{ secrets.CACHE_CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        TITLE: BFR Manager
      run: |
        export VERSION=$(date +%m%d)
        FILE=$(find ./APKs/* -type f)
        pip3 install python-telegram-bot
        python3 docs/tubot.py $FILE