name: Build APKs

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get tags
      id: get_head
      run: |
        echo "head=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 19

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Build Release APK
      id: build_apk
      run: ./gradlew app:assembleRelease
    
    - name: Pull Changes
      run: git pull
    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update apk"
        git push
    #- name: Display files in directory
    #  run: |
    #    ls app/build/outputs/apk/release

    #- uses: r0adkll/sign-android-release@v1
    #  name: Sign app APK
    #  id: sign_apks
    #  with:
    #    releaseDirectory: app/build/outputs/apk/release
    #    signingKeyBase64: ${{ secrets.KEYSTORE_CONTENT }}
    #    alias: key.alias
    #    keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    #    keyPassword: ${{ secrets.KEY_PASSWORD }}

    #- name: Rename Apks
    #  run: |
    #    mkdir -p APKs
    #    mv ${{ steps.build_apk.outputs.signedReleaseFile }} APKs/box-manager-${{ steps.get_head.outputs.head }}-prerelease.apk

    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: signed_apps
    #    path: APKs

    #- name: Delete current Prerelease-alpha assets
    #  if: ${{ github.ref_name == 'master' && github.event_name != 'pull_request' }}
    #  uses: andreaswilli/delete-release-assets-action@v2.0.0
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    tag: Prerelease-alpha
    #    deleteOnlyFromDrafts: false

    #- name: Tag Repo
    #  if: ${{ github.ref_name == 'master' && github.event_name != 'pull_request' }}
    #  uses: richardsimko/update-tag@v1
    #  with:
    #    tag_name: Prerelease-alpha
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Upload Prerelease-alpha
    #  if: ${{ github.ref_name == 'master' && github.event_name != 'pull_request' }}
    #  uses: softprops/action-gh-release@v1
    #  with:
    #    tag: ${{ github.ref_name }}
    #    tag_name: Prerelease-alpha
    #    files: APKs/*
    #    prerelease: true
    #    generate_release_notes: true

    
